### PR TITLE
Added Miki's name

### PR DESCRIPTION
**Pull request by mrezentes**
connects to https://github.com/mrezentes/codegirls/issues/1

### CODE REVIEW

**Comment by KateRezentes** [comment]
:+1:

**Comment by frezentes** [comment]
looks good

**Comment by rwdaigle** [comment]
This change has too much Miki :-1:

**Comment by KateRezentes** [comment]
You're a dweeb

**Comment by mrezentes** [comment]
_leaves her kids to do the dirty work_

**Comment by rwdaigle** [comment]
@mrezentes great job teaching the offspring how to :troll:

**Comment by mrezentes** [comment]
I don't think they would have had more fun trolling anyone as they had trolling you @rwdaigle .  You have a reputation.  There was lots of giggling.

**Pull request merged**
